try{
    hello();
}catch(error){
    console.log(error);
}


try{
    hello();
}catch{
    console.log('Se presento un error');
}

